blockExoticSubdeps: false
allowBuilds:
  '@rodrigo-barraza/components-library': true
  '@rodrigo-barraza/utilities-library': true
  sharp: true
  '@rodrigo-barraza/components-library@https://codeload.github.com/rodrigo-barraza/components-library/tar.gz/77cc8894ece262bcfbd8ab710d32068fedc82057': true
  '@rodrigo-barraza/utilities-library@https://codeload.github.com/rodrigo-barraza/utilities-library/tar.gz/eb72517ec56b4c2735bf0f5605bacbae99fa62e3': true
