import type { MemberPageData, NewgroundsProfile } from "@/types";

export const ngProfile: NewgroundsProfile = {
  username: "StrawberryClock",
  usernameLower: "strawberryclock",
  avatarUrl: "https://uimg.ngfiles.com/profile/15/15277.jpg",
  bannerUrl: null,
  profileUrl: "https://strawberryclock.newgrounds.com",
  description: "IM STRAWBERRYCLOCK HAHAHA",
  level: 14,
  rank: "Civilian",
  globalRank: 95995,
  expPoints: "2,066 / 2,180",
  expRank: 33731,
  blams: 14,
  saves: 44,
  votePower: "5.62 votes",
  fans: 2900,
  medals: 72,
  trophies: 21,
  sex: "Male",
  age: null,
  location: null,
  job: null,
  joinDate: "2000-03-22",
  realName: null,
  school: null,
  supporter: "1y 1m",
  links: [{ url: "http://www.clockcrew.net", text: "Spoony Bard" }],
  movieCount: 39,
  gameCount: 8,
  audioCount: 1,
  reviewCount: 13,
  postCount: 125,
  faveCount: 10,
  newsCount: 15,
};

export function memberData(
  overrides: Partial<MemberPageData> = {},
): MemberPageData {
  return {
    member: {
      username: "StrawberryClock",
      userId: 3,
      avatarUrl: "https://clockcrew.net/talk/custom_avatar/sbc_train.gif",
      ccForum: {
        userId: 3,
        username: "StrawberryClock",
        avatarUrl: "https://clockcrew.net/talk/custom_avatar/sbc_train.gif",
        customTitle: "King of the Portal",
        position: null,
        group: null,
        postCount: 18,
        personalText: null,
        dateRegistered: "2000-03-22T15:00:00.000Z",
        age: 50,
        gender: null,
        location: null,
        onlineStatus: "Offline",
        profileUrl: "https://clockcrew.net/talk/index.php?action=profile;u=3",
        signature: "[flash]b.swf[/flash]",
        website: null,
        lastActive: null,
      },
      newgrounds: {
        ...ngProfile,
        links: ngProfile.links.map((link) => ({ ...link })),
      },
      profileSummary: {
        markdown: "# StrawberryClock\n\nThe **King** of the portal.",
        generatedAt: null,
        model: "qwen",
        status: "complete",
      },
    },
    movies: [],
    games: [],
    audio: [],
    art: [],
    reviews: [
      {
        _id: "r1",
        reviewId: 16421464,
        body: "Hell yeah, Dave's back!",
        score: 5,
        reviewedTitle: "Cats Against Humanity",
        reviewedUrl: "https://www.newgrounds.com/portal/view/892724",
      },
    ],
    favorites: [],
    news: [],
    fans: ["Foreverkul"],
    ngPosts: [
      {
        _id: "p1",
        postId: 26988225,
        title: "What does the Clock Crew do outside of Clock day?",
        contentUrl: "https://www.newgrounds.com/bbs/post/goto/26988225",
      },
    ],
    ccPosts: [
      {
        _id: "c1",
        messageId: 1,
        topicId: 10,
        body: "god bb10",
        date: "2014-07-09T04:21:55.000Z",
        threadTitle: "DAE",
      },
    ],
    ccThreads: [
      {
        _id: "t1",
        topicId: 18942,
        title: "No More Water.",
        totalPosts: 74,
        url: "https://clockcrew.net/talk/index.php?topic=18942.0",
      },
    ],
    ccThreadCount: 1,
    ...overrides,
  };
}
